name: 'Docker Pull Auto Action'
description: 'Docker Pull Auto action works with https://github.com/codebysandip/docker-pull-auto'
inputs:
  docker-image:
    description: 'docker image. Example sandipj/react-ssr-doc'
    required: true
  docker-tag:
    description: 'docker tag which you just generated. Example latest'
    required: true
  domain:
    description: 'domain on which request will send'
    required: true
  hook-secret:
    description: 'hook secret used to verify request coming from docker pull auto action'
    required: true
  over-http:
    description: 'request will send over http if true'
    default: false
  port:
    description: 'port on which request will send. Default 443'
    default: 443
runs:
  using: 'node16'
  main: 'dist/index.js'